Moving additional paths into top level of object
apinf/restivus-swagger pull request #19
Opened 2017-05-22 17:57 UTC by dcantatore

As noted here:
https://github.com/apinf/restivus-swagger/issues/18

2017-05-23 06:58 UTC, brylie requested changes

2017-05-23 06:58 UTC, brylie commented on server/restivus-swagger.js
> +        if(swagger.paths){
Use consistent whitespace. This should be `if (condition) {`

2017-05-23 06:58 UTC, brylie commented
This looks fine. Lets just clean up the whitespace in the file, so that it is consistent. Previously, we had just one developer writing the plugin, but now we have multiple contributors.

2017-05-25 13:24 UTC, dcantatore commented
@brylie I have the whitespace corrected file ready for a PR, should I kill this PR and create another?

2017-05-26 07:48 UTC, brylie commented
We can still work from this PR, as long as you are making changes to the same branch. Is this PR ready for review?

2017-05-26 11:34 UTC, dcantatore commented
Same branch

2017-05-26 11:45 UTC, brylie approved these changes

2017-05-26 11:45 UTC, merged